deployment:
  imageURL: 485067906741.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue
  imageVersion: 1.0.0
hpa:
  maxReplicas: 10
  utilisation: 75
configMap:
  MONGO_URL: mongodb://mongodb:27017/catalogue 